### ISSUE TITLE
Complete set up of codeflare-common repo

### ISSUE THREAD

**Issue by Fiona-Waters** [project-codeflare/codeflare-common#2]
## WHY
To complete the set up of the codeflare-common repo.
## WHAT
Set up openshift-ci
Add relevant PR checks
Add OWNERS files with reviewers/approvers

## DONE
The repo will have openshift-ci set up, relevant checks added to be run on each PR, owners file added.

**Comment by sutaakar** [comment]
@Fiona-Waters OpenShift CI is implemented for common repository.
Is there anything more to be done, or can this issue be closed?

**Comment by Fiona-Waters** [comment]
> @Fiona-Waters OpenShift CI is implemented for common repository. Is there anything more to be done, or can this issue be closed?

@sutaakar I don' think there is anything more - closing it. Thanks!
